# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170929_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 29, 14, 35, 22, 419000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 29, 14, 35, 22, 419000, tzinfo=utc), null=True),
        ),
    ]
